import React, { Fragment } from 'react';
import Head from 'next/head';
import Link from 'next/link';

import GenImageForm from '../components/Main/GenImageForm';

import styles from '../styles/generate.module.css';

function generate() {
  return (
    <Fragment>
      <Head>
        <title>WordArtGen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={`${styles.Cont}`}>
        <div className={`${styles.topbar}`}>
          <Link href='/' className={`${styles.link}`}>
            <h1>WordArtGen</h1>
          </Link>
        </div>
        <GenImageForm />
      </div>
    </Fragment>
  );
}

export default generate;
